# Generated by Django 2.1.2 on 2018-10-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('portfolio', models.CharField(max_length=50)),
                ('cluster', models.CharField(max_length=50)),
                ('specific_activity', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('donor_1', models.CharField(max_length=50)),
                ('donor_2', models.CharField(max_length=50)),
                ('donor_3', models.CharField(max_length=50)),
                ('activity_value', models.IntegerField()),
                ('beneficiaries', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Category'),
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Location'),
        ),
        migrations.AddField(
            model_name='activities',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SDG'),
        ),
        migrations.AddField(
            model_name='activities',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Topic'),
        ),
    ]
