# Generated by Django 2.1.7 on 2019-03-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('portfolio', models.CharField(max_length=50)),
                ('cluster', models.CharField(max_length=50)),
                ('specific_activity', models.CharField(max_length=300)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_value', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiaries', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='categories',
            field=models.ManyToManyField(to='activities.Category'),
        ),
        migrations.AddField(
            model_name='activities',
            name='donor_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_1', to='activities.Donor'),
        ),
        migrations.AddField(
            model_name='activities',
            name='donor_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_2', to='activities.Donor'),
        ),
        migrations.AddField(
            model_name='activities',
            name='donor_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_3', to='activities.Donor'),
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='activities.Location'),
        ),
        migrations.AddField(
            model_name='activities',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SDG'),
        ),
        migrations.AddField(
            model_name='activities',
            name='sublocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublocation', to='activities.Location'),
        ),
        migrations.AddField(
            model_name='activities',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Topic'),
        ),
    ]
