# Generated by Django 2.1.2 on 2019-12-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activities_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='donor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_1', to='activities.Donor'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='donor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_2', to='activities.Donor'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='donor_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_3', to='activities.Donor'),
        ),
    ]
