# Generated by Django 2.1.4 on 2018-12-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20181031_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='sublocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublocation', to='activities.Location'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='activities.Location'),
        ),
    ]
