# Generated by Django 2.1.4 on 2018-12-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20181205_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_value',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
