version: '3.1'

services:

  service:
    build: ./service
    volumes:
      - ./service/src:/app/
    restart: always
    environment:
      DATABASE_NAME: activities
      DATABASE_USER: postgres
      DATABASE_PASSWORD: example
      DATABASE_HOST: postgres
    ports:
      - 8300:8000

  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: activities
      POSTGRES_PASSWORD: example
    volumes:
      - ./sql/initdb:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data
