version: '3.5'

services:

  app:
    build: ./service
    volumes:
      - ./service/src:/app/
    restart: always
    env_file: &envfile
      - ./.env
    ports:
      - 8300:80
    depends_on:
      - database

  database:
    image: postgres:10-alpine
    restart: always
    env_file: *envfile
    volumes:
      - ./sql/initdb:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data
