version: '3.1'

services:

  service:
    build: ./service
    volumes:
      - ./service/src:/app/
    environment:
      DATABASE_NAME: activities
      DATABASE_USER: postgres
      DATABASE_PASSWORD: example
      DATABASE_HOST: postgres
    ports:
      - 8000:8000

  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: activities
      POSTGRES_PASSWORD: example
